### ISSUE TITLE
main default branch olusturulmasi

### ISSUE THREAD

**Issue by EralpKocas** [acikkaynak/depremadres-intent-classification-v0#1]
ilk commit atarken main branch acmayi unuttum. su anda da devretmem gerekiyor. bir main branch acip default olarak guncellerseniz, cok iyi olur. tesekkurler.

**Comment by ediziks** [comment]
PR uzerinden yeni branch olusturmak mumkun degil gibi gozukuyor. Muhtemelen contributorler tarafindan yapilmasi gerek. 

ref -> https://stackoverflow.com/a/43843507

**Comment by Spawnfile** [comment]
Yeni bir `master` branchi acılıp mevcutta bulunan dosyalar merge edilebilir. @ediziks ilgili linkteki yorum da benzer bilgi vermiş, repo exist olduktan sonra merge etme konusunda sorun olmuyor.
