### ISSUE TITLE
psycopg2 Connection Error// Documentation Requiered

### ISSUE THREAD

**Issue by yunusemreemik** [acikkaynak/depremadres-intent-classification-v0#15]
AttributeError
module 'psycopg2' has no attribute 'connection'
  File "C:\Users\YUNUS\Documents\indent-earthquake\depremadres-intent-classification-v0\intent-classification-v0\pg_ops.py", line 7, in <module>
    def get_data(conn: psycopg2.connection, table_name: str, column_names: List[str], condition: str) -> List[Tuple]:
  File "C:\Users\YUNUS\Documents\indent-earthquake\depremadres-intent-classification-v0\intent-classification-v0\main.py", line 2, in <module>
    import pg_ops
AttributeError: module 'psycopg2' has no attribute 'connection'

**Comment by ybgirgin3** [comment]
bnkz: https://stackoverflow.com/a/43768050/20414260

bu ya da buna benzer bir çözümün iş görmesi gerekli

**Comment by ozkanuysal** [comment]
Logger kısmı için de aynı sıkıntısı olan durum varmış bu şekilde çözüme ulaştırmışlar yardımcı olabilir diye bırakıyorum.

Link : https://groups.google.com/g/sqlalchemy/c/hwAM3nPc_co

**Comment by yunusemreemik** [comment]
Postgre bağlantısını sağlayan kütüphane connectionstring bilgisini güvenlik dolayısı ile gömülü bir dosyadan almakta.
Bu beklenen bir hata çıktısı. Fakat Readme kısmında belirtilmeli contact paylaşılmalıdır.
Zero shot api key için yönlendirici bir dokümantasyon gerekmekte.
