### ISSUE TITLE
cosine similarity

### ISSUE THREAD

**Issue by yilmazalp** [acikkaynak/depremadres-intent-classification-v0#32]
Her tweet ve yemek, kurtarma, giysi txt arasında cosine similarity hesapladım. Bunun data frame'ini oluşturdum. Dosya upload edemediğim için buraya yazıyorum. Projeye katkı sağlar mı bilmiyorum ama buraya colab linkini bırakıyorum(.ipynb dosyası):

https://colab.research.google.com/drive/1S8UUXPQv87xCjMxoDoXgiKOyuet1pQU7?usp=sharing

**Comment by yunusemreemik** [comment]
Teşekkürler Yılmaz elbette işimize yarayabilir. Bunun için usefull_links.txt isimli bir dosya ekleyebiliriz. PR açabilirsen inceleyip dönbüş yapalım. Şimdilik kapayabilirsin.

**Comment by yilmazalp** [comment]
Teşekkürler :)
